### ISSUE TITLE
Can't Select Child Item When there exists only 1 Child Item

### ISSUE THREAD

**Issue by MiiNoe879** [ndamjan/vuetify-treeview-example#3]
If the item has only 1 child item(that has no children), when I try to select child item, parent item is selected though I have selected child item.
After the parent item had been selected I can select the child item as I want.
Can anyone please help me?

**Comment by MiiNoe879** [comment]
Sorry, not yet.
Maybe @ndamjan will help us.

**Comment by ndamjan** [comment]
Hi, thanks for catching this!
The issue was that single select was behaving like checkbox for this case. 

To prevent this, I added an additional condition in the watcher for `allDescendantLeafsSelected`:

![screen shot 2018-09-25 at 08 43 23](https://user-images.githubusercontent.com/5169234/45997393-aecfff00-c09f-11e8-9169-b24db92531b4.png)

I pushed the fix to this repository and added an example.

**Comment by kdevsoftware** [comment]
Thanks @ndamjan.
I did and it works well.

**Comment by Sim923** [comment]
Great! @ndamjan 
It works well.
